from .conditioning_nodes import (
    NODE_CLASS_MAPPINGS as CONDITIONING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CONDITIONING_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lmstudio_nodes import (
    NODE_CLASS_MAPPINGS as LMSTUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lora_nodes import (
    NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .model_loader_nodes import (
    NODE_CLASS_MAPPINGS as MODEL_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MODEL_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .selector_nodes import (
    NODE_CLASS_MAPPINGS as SELECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .text_nodes import (
    NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .utility_nodes import (
    NODE_CLASS_MAPPINGS as UTILITY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
)

# MetaView (novel-view synthesis) nodes. These modules import vendored helpers
# package-relative with a top-level fallback (see metaview_model.py), so mirror
# that pattern here: prefer the package-relative import, fall back to top-level
# when the pack is loaded as a bare module directory.
try:  # loaded as part of the node pack (package-relative)
    from .metaview_model import (
        NODE_CLASS_MAPPINGS as METAVIEW_MODEL_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as METAVIEW_MODEL_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from .metaview_conditioning import (
        NODE_CLASS_MAPPINGS as METAVIEW_COND_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as METAVIEW_COND_NODE_DISPLAY_NAME_MAPPINGS,
    )
except ImportError:  # loaded as a top-level module
    from metaview_model import (
        NODE_CLASS_MAPPINGS as METAVIEW_MODEL_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as METAVIEW_MODEL_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from metaview_conditioning import (
        NODE_CLASS_MAPPINGS as METAVIEW_COND_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as METAVIEW_COND_NODE_DISPLAY_NAME_MAPPINGS,
    )

NODE_CLASS_MAPPINGS = {
    **CONDITIONING_NODE_CLASS_MAPPINGS,
    **TEXT_NODE_CLASS_MAPPINGS,
    **LMSTUDIO_NODE_CLASS_MAPPINGS,
    **LORA_NODE_CLASS_MAPPINGS,
    **MODEL_LOADER_NODE_CLASS_MAPPINGS,
    **SELECTOR_NODE_CLASS_MAPPINGS,
    **UTILITY_NODE_CLASS_MAPPINGS,
    **METAVIEW_MODEL_NODE_CLASS_MAPPINGS,
    **METAVIEW_COND_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CONDITIONING_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **MODEL_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
    **METAVIEW_MODEL_NODE_DISPLAY_NAME_MAPPINGS,
    **METAVIEW_COND_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
