from .lmstudio_nodes import (
    NODE_CLASS_MAPPINGS as LMSTUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lora_nodes import (
    NODE_CLASS_MAPPINGS as LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .selector_nodes import (
    NODE_CLASS_MAPPINGS as SELECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .text_nodes import (
    NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .utility_nodes import (
    NODE_CLASS_MAPPINGS as UTILITY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **TEXT_NODE_CLASS_MAPPINGS,
    **LMSTUDIO_NODE_CLASS_MAPPINGS,
    **LORA_NODE_CLASS_MAPPINGS,
    **SELECTOR_NODE_CLASS_MAPPINGS,
    **UTILITY_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **UTILITY_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
