from .lmstudio_nodes import (
    NODE_CLASS_MAPPINGS as LMSTUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .text_nodes import (
    NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **TEXT_NODE_CLASS_MAPPINGS,
    **LMSTUDIO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **LMSTUDIO_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
